apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vue-xs-admin-hpa
  namespace: vue-xs-admin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vue-xs-admin-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
